#!/usr/bin/env python
# -*- coding: utf-8 -*-
import gtk
import webkit
win = gtk.Window()
win.connect("destroy", gtk.main_quit)
url = webkit.WebView()
#win.set_size_request(gtk.gdk.screen_width(),gtk.gdk.screen_height())
win.set_size_request(855, 528)
win.set_position(gtk.WIN_POS_CENTER)
win.set_resizable(0)
win.set_icon_from_file("/usr/share/pixmaps/kuttab.png")
win.set_title("كُتّاب - التدريب على الطباعة العربية")
settings = url.get_settings()
settings.set_property('enable-file-access-from-file-uris', 1)
settings.set_property('enable-default-context-menu',1)
url.open("file:///usr/share/kuttab/index.html")
win.add(url)
win.show_all()
gtk.main()
